[build]
target = "riscv64gc-unknown-none-elf"

[target.riscv64gc-unknown-none-elf]
rustflags = [
    "-C", "link-arg=-Tlinker.ld",
]

runner = [
    "qemu-system-riscv64",
    "-machine", "virt",
    "-smp", "1",
    "-m", "128M",
    "-nographic",
    "-bios", "default",
    "-global", "virtio-mmio.force-legacy=false",
    "-drive", "file=build/fat12.img,format=raw,id=hd0,if=none",
    "-device", "virtio-blk-device,drive=hd0",
    "-kernel",
]
